# Generated by Django 5.0.1 on 2024-02-07 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 16, 25, 17, 505824, tzinfo=datetime.timezone.utc)),
        ),
    ]
