# Generated by Django 5.0.1 on 2024-02-10 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank='True', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 28, 41, 125182, tzinfo=datetime.timezone.utc)),
        ),
    ]
