# Generated by Django 5.0.1 on 2024-02-10 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 17, 32, 58, 250152, tzinfo=datetime.timezone.utc)),
        ),
    ]
