# Generated by Django 5.0.1 on 2024-02-10 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 17, 33, 38, 520036, tzinfo=datetime.timezone.utc)),
        ),
    ]
