# Generated by Django 5.0.1 on 2024-02-15 11:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_publish_comment_post_comment_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 11, 9, 45, 574819, tzinfo=datetime.timezone.utc)),
        ),
    ]
