# Generated by Django 5.0.1 on 2024-02-15 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_user_like_comment_rename_comment_post_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 11, 11, 45, 111483, tzinfo=datetime.timezone.utc)),
        ),
    ]
